kind: Added
body: Make the worker use baggageclaim overlay driver by default + adjust default
  resources + show useful nodeSelector option
time: 2022-04-15T16:31:47.247942149+02:00
custom:
  Ref: Pull
  RefID: "132"
