kind: Changed
body: 'redis: Moving away from Bitnami due to their recent announcement of changes, Cycloid now uses a local chart to manage a standalone Redis.'
time: 2025-08-21T15:53:24.119244488+02:00
custom:
    Ref: Pull
    RefID: "235"
