---

- name: Stop services | cycloid-core
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - cycloid-api_container
    - cycloid-frontend_container
    - nginx_container
    - docker
  failed_when: false

- name: Remove files | cycloid-core
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ concourse_config_path }}"
    - "{{ cycloid_install_path }}"
    - /etc/systemd/system/cycloid-api_container.service
    - /etc/systemd/system/cycloid-frontend_container.service
    - /etc/default/cycloid-api
    - /etc/default/cycloid-frontend
    - /etc/systemd/system/nginx_container.service
    - /etc/systemd/system/docker.service
    - /var/lib/docker
    - /opt/containerd

- name: Remove packages | cycloid-core
  package:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker*
  failed_when: false

- name: Force systemd to reread configs | cycloid-core
  systemd:
    daemon_reload: yes

- name: systemctl reset-failed | cycloid-core
  shell: systemctl reset-failed
