---
- name: Stop services | cycloid-scheduler-db
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - concourse-db
    - docker
  failed_when: false

- name: Remove packages | cycloid-scheduler-db
  package:
    name:
      - docker*
    state: absent
  failed_when: false
  when: setup_packages

- name: Remove files | cycloid-scheduler-db
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ concourse_db_path }}"
    - "{{ cycloid_install_path }}"
    - /etc/systemd/system/concourse-db_container.service
    - /etc/default/concourse-db
    - /etc/systemd/system/docker.service
    - /var/lib/docker
    - /opt/containerd

- name: Force systemd to reread configs | cycloid-scheduler-db
  systemd:
    daemon_reload: yes

- name: systemctl reset-failed | cycloid-scheduler-db
  shell: systemctl reset-failed
