---

- name: Cycloid redis
  include_role:
    name: mhutter.docker-systemd-service
  vars:
    name: cycloid-redis
    container_docker_pull: "{{ docker_pull }}"
    container_image: "{{ cycloid_redis_image }}"
    container_ports:
      - '{{ cycloid_email_redis_port }}:6379'
    container_volumes:
      - "{{cycloid_redis_path}}:/data"
  tags: docker-services
