{{- if .Values.frontend.enabled }}
{{- if .Values.frontend.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "frontend.serviceAccountName" . }}
  labels:
    {{- include "cycloid.labels" . | nindent 4 }}
    {{- include "frontend.selectorLabels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or .Values.frontend.serviceAccount.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.frontend.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
