---
- name: Install Kibana
  hosts: all
  become: true
  roles:
    - role: geerlingguy.kibana
  vars:
    kibana_version: "7.x"
    kibana_package: kibana=7.17.0
    kibana_server_port: 5601
    kibana_server_host: "0.0.0.0"
    kibana_elasticsearch_url: "http://localhost:9200"