---
- name: Install Elasticsearch
  hosts: all
  become: true
  roles:
    - role: elastic.elasticsearch
  vars:
    es_version: 7.17.0
    es_config:
      http.host: 0.0.0.0
    es_enable_http_ssl: true
    es_enable_transport_ssl: true
    es_enable_auto_ssl_configuration: true
    es_api_basic_auth_username: "elastic" # This is the default user created by the installation of elasticsearch
    es_api_basic_auth_password: "changeme" # This is the default password created by the installation of elasticsearch
    es_users:
    native:
      elastic:
        password: "Co$T-Exp10râ‚¬r" # New password
    es_validate_certs: no 