apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: {{ printf "%s-master" (include "redis.common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.common.labels" . | nindent 4 }}
    {{- include "redis.selectorLabels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels: {{- include "redis.selectorLabels" . | nindent 6 }}
  serviceName: {{ printf "%s-headless" (include "redis.common.names.fullname" .) }}
  updateStrategy:
    type: "RollingUpdate"
  minReadySeconds: 0
  template:
    metadata:
      labels:
        {{- include "redis.common.labels" . | nindent 8 }}
        {{- include "redis.selectorLabels" . | nindent 8 }}
      annotations:
      {{- if .Values.commonAnnotations }}
        {{- with .Values.commonAnnotations }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      {{- end }}
        checksum/health: {{ pick ( include (print $.Template.BasePath "/health-configmap.yaml") . | fromYaml ) "data" | toYaml | sha256sum }}
        checksum/secret: {{ pick ( include (print $.Template.BasePath "/secret.yaml") . | fromYaml ) "data" | toYaml | sha256sum }}
    spec:
      securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: Always
      serviceAccountName: {{ template "redis.masterServiceAccountName" . }}
      automountServiceAccountToken: false
      {{- if .Values.master.nodeSelector }}
      nodeSelector: {{- include "redis.master.nodeSelector" . | nindent 8 }}
      {{- end }}
      enableServiceLinks: true
      terminationGracePeriodSeconds: 30
      containers:
        - name: redis
          image: {{ template "redis.image" . }}
          command: ["redis-server"]
          args: ["/usr/local/etc/redis/redis.conf"]
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            {{- if .Values.auth.enabled }}
            # used by liveness prob
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "redis.secretName" . }}
                  key: {{ template "redis.secretPasswordKey" . }}
            {{- end }}
          ports:
            - name: redis
              containerPort: 6379
          livenessProbe:
            initialDelaySeconds: {{ .Values.master.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.master.livenessProbe.periodSeconds }}
            # One second longer than command timeout should prevent generation of zombie processes.
            timeoutSeconds: {{ add1 .Values.master.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.master.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.master.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -ec
                - "/health/ping_liveness_local.sh {{ .Values.master.livenessProbe.timeoutSeconds }}"
          readinessProbe:
            initialDelaySeconds: {{ .Values.master.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.master.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ add1 .Values.master.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.master.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.master.readinessProbe.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -ec
                - "/health/ping_readiness_local.sh {{ .Values.master.readinessProbe.timeoutSeconds }}"
          {{- if .Values.master.resources }}
          resources: {{- toYaml .Values.master.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: health
              mountPath: /health
            - name: redis-data
              mountPath: /data
            {{- if .Values.tls.enabled }}
            - name: redis-certificates
              mountPath: /ssl
              readOnly: true
            {{- end }}
            - name: config
              mountPath: /usr/local/etc/redis/redis.conf
              subPath: redis.conf
      volumes:
        - name: config
          secret:
            secretName: {{ template "redis.common.names.fullname" . }}-conf
        - name: health
          configMap:
            name: {{ printf "%s-health" (include "redis.common.names.fullname" .) }}
            defaultMode: 0755
        {{- if .Values.tls.enabled }}
        - name: redis-certificates
          secret:
            secretName: {{ include "redis.tlsSecretName" . }}
            defaultMode: 256
        {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: redis-data
        labels:
          {{- include "redis.common.labels" . | nindent 10 }}
          {{- include "redis.selectorLabels" . | nindent 10 }}
        {{- if .Values.commonAnnotations }}
        annotations:
          {{- with .Values.commonAnnotations }}
            {{- toYaml . | nindent 4 }}
          {{- end }}
        {{- end }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.master.persistence.size | quote }}
        {{- include "redis.storage.class" . | nindent 8 }}