apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-master" (include "redis.common.names.fullname" .) }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.common.labels" . | nindent 4 }}
    {{- include "redis.selectorLabels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: "tcp-redis"
      port: 6379
      targetPort: redis
      nodePort: null
  selector: {{- include "redis.selectorLabels" . | nindent 4 }}