apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.common.names.fullname" . }}-conf
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.common.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
stringData:
  redis.conf: |
    {{- if .Values.auth.enabled }}
    requirepass "{{ .Values.auth.password }}"
    {{- end }}

    {{- if .Values.tls.enabled }}
    tls-auth-clients no
    port 0
    tls-port 6379
    tls-cert-file {{ template "redis.tlsCert" . }}
    tls-key-file {{ template "redis.tlsCertKey" . }}
    tls-ca-cert-file {{ template "redis.tlsCACert" . }}
    {{- end }}