{{- if (include "redis.createTlsSecret" .) }}
{{- $secretName := include "redis.tlsSecretName" . }}
{{- $ca := genCA "redis-ca" 3650 }}
{{- $releaseNamespace := .Release.Namespace }}
{{- $clusterDomain := "cluster.local" }}
{{- $fullname := include "redis.common.names.fullname" . }}
{{- $serviceName := include "redis.common.names.fullname" . }}
{{- $headlessServiceName := printf "%s-headless" (include "redis.common.names.fullname" .) }}
{{- $masterServiceName := printf "%s-master" (include "redis.common.names.fullname" .) }}
{{- $altNames := list (printf "*.%s.%s.svc.%s" $serviceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $masterServiceName $releaseNamespace $clusterDomain) (printf "*.%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) (printf "%s.%s.svc.%s" $headlessServiceName $releaseNamespace $clusterDomain) "127.0.0.1" "localhost" $fullname }}
{{- $cert := genSignedCert $fullname nil $altNames 3650 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis.common.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ include "redis.secrets.lookup" (dict "secret" $secretName "key" "tls.crt" "defaultValue" $cert.Cert "context" $) }}
  tls.key: {{ include "redis.secrets.lookup" (dict "secret" $secretName "key" "tls.key" "defaultValue" $cert.Key "context" $) }}
  ca.crt: {{ include "redis.secrets.lookup" (dict "secret" $secretName "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
{{- end }}
