apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.primary.fullname" . }}-poststart-script
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  postStartScript.sh:
    {{- toYaml .Values.primary.postStartScript | nindent 4 }}