{{- if .Values.primary.configuration }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mysql.primary.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  my.cnf:
    {{- toYaml .Values.primary.configuration | nindent 4 }}
{{- end }}