{{- $host := include "mysql.primary.fullname" . }}
{{- $port := print .Values.primary.service.ports.mysql }}
{{- $database := print .Values.auth.database }}
{{- $username := print .Values.auth.username }}
{{- $password := include "mysql.password" . }}
{{- $rootPassword := include "mysql.rootPassword" . }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.primary.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: Opaque
data:
  mysql-root-password: {{ print $rootPassword  | b64enc | quote }}
  mysql-password: {{ print $password | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mysql.primary.fullname" . }}-svcbind-custom-user
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
type: servicebinding.io/mysql
data:
  provider: {{ print "bitnami" | b64enc | quote }}
  type: {{ print "mysql" | b64enc | quote }}
  host: {{ print $host | b64enc | quote }}
  port: {{ print $port | b64enc | quote }}
  username: {{ print $username | b64enc | quote }}
  database: {{ print $database | b64enc | quote }}
  password: {{ print $password | b64enc | quote }}
  uri: {{ printf "mysql://%s:%s@%s:%s/%s" $username $password $host $port $database | b64enc | quote }}

