apiVersion: "apps/v1"
kind: StatefulSet
metadata:
  name: {{ include "mysql.primary.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels: {{- include "mysql.selectorLabels" . | nindent 6 }}
  serviceName: {{ printf "%s-headless" (include "mysql.primary.fullname" .) }}
  updateStrategy:
    type: "RollingUpdate"
  template:
    metadata:
      annotations:
      {{- if .Values.commonAnnotations }}
        {{- with .Values.commonAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.primary.configuration }}
        checksum/config: {{ pick ( include (print $.Template.BasePath "/configmap.yaml") . | fromYaml ) "data" | toYaml | sha256sum }}
      {{- end }}
      labels:
        {{- include "mysql.labels" . | nindent 8 }}
        {{- include "mysql.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mysql.primary.fullname" . }}
      automountServiceAccountToken: {{ .Values.primary.automountServiceAccountToken }}
      {{- if .Values.primary.nodeSelector }}
      nodeSelector:
        {{- with .Values.primary.nodeSelector }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      {{- if .Values.primary.podSecurityContext.enabled }}
      securityContext:
        fsGroupChangePolicy: Always
        fsGroup: 1001
      {{- end }}
      containers:
        - name: mysql
          image: {{ template "mysql.image" . }}
          # TMP This is used to migrate from bitnami to official image. It will be removed on the next release
          command:
            - /bin/bash
            - -ec
            - |
              if [ -d "/var/lib/mysql/data" ]; then
                echo "Migrating existing data directory..."
                mv /var/lib/mysql/data/* /var/lib/mysql/ || true
                rmdir /var/lib/mysql/data || true
              fi
              exec docker-entrypoint.sh mysqld
          ###
          {{- with .Values.primary.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          {{- if .Values.primary.containerSecurityContext.enabled }}
          securityContext:
            seLinuxOptions: {}
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            seccompProfile:
              type: "RuntimeDefault"
            readOnlyRootFilesystem: true
          {{- end }}
          env:
            - name: MYSQL_PORT
              value: {{ .Values.primary.containerPorts.mysql | quote}}
            - name: MYSQL_DATABASE
              value: {{ .Values.auth.database | quote }}
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.primary.fullname" . }}
                  key: mysql-root-password
            #- name: MYSQL_ENABLE_SSL
            #  value: {{ ternary "yes" "no" .Values.tls.enabled | quote }}
            #{{- if and .Values.tls.enabled (include "mysql.tlsCACert" .) }}
            #- name: MYSQL_CLIENT_CA_FILE
            #  value: {{ include "mysql.tlsCACert" . | quote }}
            #{{- end }}
            {{- if not (empty .Values.auth.username) }}
            - name: MYSQL_USER
              value: {{ .Values.auth.username | quote }}
            {{- end }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mysql.primary.fullname" . }}
                  key: mysql-password
            {{- include "cycloid.extraEnvVars" .Values | nindent 12 }}
          ports:
            - name: mysql
              containerPort: {{ .Values.primary.containerPorts.mysql }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.primary.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.primary.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  mysqladmin status -uroot -p"${MYSQL_ROOT_PASSWORD}"
          readinessProbe:
            initialDelaySeconds: {{ .Values.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.primary.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.primary.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  mysqladmin ping -uroot -p"${MYSQL_ROOT_PASSWORD}" | grep "mysqld is alive"
            startupProbe:
            initialDelaySeconds: {{ .Values.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.primary.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.primary.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.primary.livenessProbe.failureThreshold }}
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  mysqladmin ping -uroot -p"${MYSQL_ROOT_PASSWORD}" | grep "mysqld is alive"
          resources: {{ toYaml .Values.primary.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            {{- if .Values.tls.enabled }}
            - name: empty-dir
              mountPath: /var/lib/mysql/certs
            {{- end }}
            - name: empty-dir
              mountPath: /tmp
            - name: empty-dir
              mountPath: /var/run/mysqld
            - name: empty-dir
              mountPath: /etc/mysql/conf.d
            - name: config
              mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
            - name: poststart-script
              mountPath: /scripts/postStartScript.sh
              subPath: postStartScript.sh
      volumes:
        - name: poststart-script
          configMap:
            name: {{ include "mysql.primary.fullname" . }}-poststart-script
        {{- if .Values.primary.configuration }}
        - name: config
          configMap:
            name: {{ include "mysql.primary.fullname" . }}
        {{- end }}
        {{- if .Values.tls.enabled }}
        - name: cert
          secret:
            secretName: {{ include "mysql.primary.fullname" . }}
            defaultMode: 256
        {{- end }}
        - name: empty-dir
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "mysql.labels" . | nindent 10 }}
          {{- include "mysql.selectorLabels" . | nindent 10 }}
        {{- if .Values.commonAnnotations }}
        annotations:
          {{- with .Values.commonAnnotations }}
            {{- toYaml . | nindent 4 }}
          {{- end }}
        {{- end }}
      spec:
        accessModes:
          {{- range .Values.primary.persistence.accessModes }}
          - {{ . | quote }}
          {{- end }}
        resources:
          requests:
            storage: {{ .Values.primary.persistence.size | quote }}
        {{- include "mysql.storage.class" . | nindent 8 }}