apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "mysql.primary.fullname" .)}}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: mysql
      port: {{ .Values.primary.containerPorts.mysql }}
      targetPort: mysql
  selector: {{- include "mysql.selectorLabels" . | nindent 4 }}
