apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql.primary.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mysql.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: mysql
      port: {{ .Values.primary.service.ports.mysql }}
      protocol: TCP
      targetPort: mysql
      nodePort: null
  selector: {{- include "mysql.selectorLabels" . | nindent 4 }}
