changesDir: changes
unreleasedDir: unreleased
headerPath: header.tpl.md
versionHeaderPath: ""
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}} ([{{.Custom.Ref}} #{{.Custom.RefID}}](https://github.com/cycloidio/ansible-cycloid-onprem/issues/{{.Custom.RefID}}))'
kinds:
- label: Added
- label: Changed
- label: Deprecated
- label: Removed
- label: Fixed
- label: Security
custom:
- key: Ref
  type: enum
  enumOptions:
  - Pull
  - Issue
- key: RefID
  type: int
  minInt: 1
replacements:
# changie replacement in Chart.yaml doesn't seem to work well with the ^
# @see https://github.com/miniscruff/changie/discussions/179
# temporary alternative set in the `scripts/release/prepare.sh` script
- path: Chart.yaml
  find: '^version: .*'
  replace: 'version: {{.VersionNoPrefix}}'
