apiVersion: v2
name: cycloid
description: A Helm chart for Cycloid, the Hybrid Cloud DevOps Collaboration Platform
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.7.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.4.4"

kubeVersion: ">= 1.19.0-0"

home: https://cycloid.io

sources:
  - https://github.com/cycloidio/ansible-cycloid-onprem

maintainers:
  - name: Cycloid DevOps team
    email: support@cycloid.io

icon: https://avatars.githubusercontent.com/u/14579210

keywords:
  - cycloid
  - devops
  - cloud
  - aws
  - gcp
  - azure
  - flexible-engine

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-mysql
    version: ~8.8.8
    condition: mysql.enabled

  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-redis
    version: ~15.4.1
    condition: redis.enabled

  - name: concourse
    repository: https://concourse-charts.storage.googleapis.com/
    tags:
      - concourse
    version: ~14.5.6
    condition: concourse.enabled

  - name: vault
    repository: https://helm.releases.hashicorp.com
    tags:
      - hashicorp-vault
    version: ~0.9.0
    condition: vault.enabled

# annotations:
#   artifacthub.io/prerelease: "{{IS_PRERELEASE}}"
