apiVersion: v2
name: cycloid
description: A Helm chart for Cycloid, the Hybrid Cloud DevOps Collaboration Platform
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.13.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "5.1.67"

kubeVersion: ">= 1.23.0-0"

home: https://cycloid.io

sources:
  - https://github.com/cycloidio/ansible-cycloid-onprem

maintainers:
  - name: Cycloid DevOps team
    email: support@cycloid.io

icon: https://avatars.githubusercontent.com/u/14579210

keywords:
  - cycloid
  - devops
  - cloud
  - aws
  - gcp
  - azure
  - flexible-engine

dependencies:
  - name: mysql
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
    tags:
      - bitnami-mysql
    # https://github.com/bitnami/charts/blob/main/bitnami/mysql/Chart.yaml#L37
    version: 11.1.19
    condition: mysql.enabled

  - name: redis
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-redis
    # https://github.com/bitnami/charts/blob/main/bitnami/redis/Chart.yaml#L39
    version: 18.5.0
    condition: redis.enabled

  - name: concourse
    repository: https://concourse-charts.storage.googleapis.com/
    tags:
      - concourse
    # https://github.com/concourse/concourse-chart/blob/master/Chart.yaml#L4
    version: 17.3.1
    condition: concourse.enabled

  - name: vault
    repository: https://helm.releases.hashicorp.com
    tags:
      - hashicorp-vault
    # https://github.com/hashicorp/vault-helm/blob/main/Chart.yaml#L6
    version: 0.27.0
    condition: vault.enabled

# annotations:
#   artifacthub.io/prerelease: "{{IS_PRERELEASE}}"
