---
roles:
#- src: https://github.com/cycloidio/ansible-prometheus.git
#  version: master
#  name: cycloid.prometheus
#  scm: git
#
#- src: https://github.com/cycloidio/ansible-telegraf.git
#  version: master
#  name: cycloid.telegraf
#  scm: git
#
#- src: https://github.com/dj-wasabi/ansible-telegraf
#  version: master
#  name: dj-wasabi.telegraf
#  scm: git

- src: git@github.com:cycloidio/ansible-cycloid-onprem.git
  version: master
  name: ansible-cycloid-onprem
  scm: git

- src: https://github.com/geerlingguy/ansible-role-docker
  version: master
  name: geerlingguy.docker
  scm: git

- src: https://github.com/mhutter/ansible-docker-systemd-service
  version: master
  name: mhutter.docker-systemd-service
  scm: git

collections:
  # Install a collection from Ansible Galaxy.
  - name: community.docker
    version: 3.10.3
    source: https://galaxy.ansible.com
