---
roles:
- src: https://github.com/cycloidio/ansible-concourse
  version: master
  name: cycloid.concourse
  scm: git

- src: git@github.com:cycloidio/ansible-cycloid-onprem.git
  version: master
  name: ansible-cycloid-onprem
  scm: git

collections:
  - name: prometheus.prometheus
    version: "0.25.0"
    source: https://galaxy.ansible.com